### ISSUE TITLE
Cannot create new config file while in Virtual Env

### ISSUE THREAD

**Issue by azeng-jwp** [rmnl/clack#9]
Hi! 
Installed Clack on local MBP, but ran into a problem with setting up a config file while inside a Virtual Env.   Runs fine when not in Virtual Env. 

Installed it to my Virtual Env via  
> pip install --upgrade clack-cli

Ran clack init and entered my information, but then fails with the traceback message.  Have also tried with sudo clack init --force
> clack init

> Traceback (most recent call last):
>   File "/Users/azeng/Desktop/upload/bin/clack", line 11, in <module>
>     sys.exit(clack())
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/clack/clack.py", line 717, in init
>     config = edit_environment(config, *args, **kwargs)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/clack/clack.py", line 140, in edit_environment
>     keyring.set_password(keyring_id(name), key, secret)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/keyring/core.py", line 47, in set_password
>     _keyring_backend.set_password(service_name, username, password)
>   File "/Users/azeng/Desktop/upload/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 37, in set_password
>     raise PasswordSetError("Can't store password on keychain")
> keyring.errors.PasswordSetError: Can't store password on keychain
> 

As mentioned, installing clack outside of Virtual Env and setting a config works.  Can access config while in virtual env after setting them up outside.

**Comment by rmnl** [comment]
@azeng-jwp Which OS are you one?

**Comment by azeng-jwp** [comment]
using macOS Sierra (10.12.5)

**Comment by rmnl** [comment]
OK, I will investigate.

**Comment by HeidiW** [comment]
I am having the same issue, is there any update on this?
